config/routes.rb
Rails.application.routes.draw do
  get 'users/prospect'
  get 'users/contacted'
  # users
  resources :users, only: [:update]
  # demos
  resources :demos do
    post :send_reminder
  end
  get '/settings', to: 'demos#settings', as: 'demo_settings'
  # availabilities
  resources :availabilities
  # leads
  resources :leads do
    member do
      patch :change_stage
      post :closed_stage
    end

    collection do
      get :new_csv
      get :new_leads
    end
  end
  get '/lead_view', to: 'leads#lead_view', as: 'lead_view'
  get '/pipeline_view', to: 'leads#pipeline_view', as: 'pipeline_view'
  # users
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords' }

  get '/confirm_phone', to: 'static#confirm_phone', as: :confirm_phone
  post '/verify_otp', to: 'static#verify_otp', as: :verify_otp
  get '/after_sign_up', to: 'static#after_sign_up', as: :after_sign_up
  get "/generate_report", to: 'static#generate_report'
  post '/add_lead', to: 'static#add_lead', as: :web_add_lead
  get '/add_domain', to: "subscriptions#add_domain"
  post '/select_domain', to: "subscriptions#select_domain"
  post '/search_domain', to: "subscriptions#search_domain"

  get 'users/:id/prospect/:lead_number', to: 'users#prospect', as: :lead_prospect
  get 'users/:id/contacted/:lead_number', to: 'users#contacted', as: :lead_contacted
  get 'users/:id/demo/:lead_number', to: 'users#demo', as: :lead_demo
  get 'users/:id/followup/:lead_number', to: 'users#followup', as: :lead_followup
  get 'users/:id/closed/:lead_number', to: 'users#closed', as: :lead_closed
  get 'users/:id/change_stage/:lead_number', to: 'users#change_stage', as: :lead_change_stage
  post '/book_demo', to:'users#book_demo'
  get '/book_new', to:'users#book_new'

  get '/pay', to: 'static#pay'

  # registrations
  devise_scope :user do
    get 'registrations/new_subscription'
    get 'registrations/add_domain'
    get 'registrations/add_leads'
    post 'registrations/select_domain'
    post 'registrations/search_domain'
  end

  # CSV import route
  post 'leads/import', to: 'leads#import'

  resources :appointments do
   collection { get :day_view }
 end

  resources :subscriptions
  get 'users/:id', to: "static#user_template"
  
  # home page
  root 'static#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/demo.rb
class Demo < ApplicationRecord
  belongs_to :user
  belongs_to :lead

  scope :month, lambda { |month|
    where(start_datetime: month.beginning_of_month.beginning_of_week..month.end_of_month.end_of_week)
  }
  scope :next_four_days, lambda { |datetime|
    where(start_datetime: datetime.beginning_of_day..(datetime + 3.days).end_of_day)
      .group_by(&:start_datetime)
  }

  def duration
    "#{start_datetime.strftime('%l:%M %P')} - #{end_time.strftime('%l:%M %P')}"
  end

  def end_time
    start_datetime + 30.minutes
  end
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  before_action :authenticate_user!, :user_authenticated?
  before_action :set_demo, only: %i[show edit update destroy send_reminder]
  skip_before_action :check_user_subscription, only: [:settings]

  # GET /demos
  def index
    start_date = params.fetch(:start_date, Date.today).to_date
    current_user_appointments = current_user.appointments.includes(:lead)
    @appointments = current_user_appointments.month(start_date)
    @next_four_days = current_user_appointments.next_four_days DateTime.now
  end

  # GET /demos/settings
  def settings
    @availabilities = current_user.availabilities
    @lead = current_user.leads.first
  end

  # POST /demos/:demo_id/send_reminder
  def send_reminder
    lead = @demo.lead
    text = "Hi #{lead.first_name}, here is the zoom link for the demo #{current_user.zoom_link}"
    if TwilioClient.new.send_text(lead.phone_number, text).sid.present?
      flash[:notice] = 'Reminder was sent successfully.'
    else
      flash[:alert] = 'Something went wrong while sending reminder. Please try again later.'
    end
    redirect_back fallback_location: root_path
  end

  # GET /prospect_chat_with/:customer_phone_number
  def prospect; end

  def contacted; end

  # GET /demos/1 or /demos/1.json
  def show; end

  # GET /demos/new
  def new
    @demo = Demo.new
  end

  # GET /demos/1/edit
  def edit; end

  # POST /demos
  def create
    @demo = Demo.new(demo_params)

    respond_to do |format|
      if @demo.save
        format.html { redirect_to @demo, notice: 'Demo was successfully created.' }
        format.json { render :show, status: :created, location: @demo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demos/1 or /demos/1.json
  def update
    respond_to do |format|
      if @demo.update(demo_params)
        format.html { redirect_to @demo, notice: 'Demo was successfully updated.' }
        format.json { render :show, status: :ok, location: @demo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demos/1 or /demos/1.json
  def destroy
    @demo.destroy
    respond_to do |format|
      format.html { redirect_to demos_url, notice: 'Demo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_demo
    @demo = Demo.find(params[:id] || params[:demo_id])
  end

  # Only allow a list of trusted parameters through.
  def demo_params
    params.require(:demo).permit(:user_id, :lead_id, :start_datetime)
  end
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/views/demos/_demo.html.erb
<div class="modal-content">
<div class="modal-header">
  <h5 class="modal-title">Demo with <%= appointment.lead.first_name %></h5>
       <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
  <b>Scheduled at:</b>  <%= appointment.start_time.strftime('%A %B %e, %Y') %>, <%= appointment.duration %>
</div>
<div class="modal-footer">
  <% if current_user.zoom_link.present? %>
    <%= link_to 'Send Demo Link Again', demo_send_reminder_path(appointment), class: 'btn btn-primary', method: :post %>
  <% else %>
    <span>Please add personal zoom <%= link_to 'here', demo_settings_path %> to send invite to lead.</span>
  <% end %>
</div>
</div>

app/views/demos/_form.html.erb
<%= form_with(model: demo) do |form| %>
  <% if demo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(demo.errors.count, "error") %> prohibited this demo from being saved:</h2>

      <ul>
        <% demo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <label>Required</label>
  <div class="row">
    <div class="col-12 col-md-6">
      <div class="form-group">
        <%= form.text_field :user_id, class: 'form-control', placeholder: 'User' %>
      </div>
    </div>
    <div class="col-12 col-md-6">
      <div class="form-group">
        <%= form.text_field :lead_id, class: 'form-control', placeholder: 'Lead' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-md-12">
      <%= form.datetime_select :start_datetime, class: 'form-control' %>
    </div>
  </div>

  <div class="col-12 p-0">
    <button type="submit" class="btn_red"><span><%= image_tag('plus1.png', alt: "#") %> Create Demo</span></button>
    <a href="/demos" class="btn_purple"><span>Back</span></a>
  </div>
<% end %>

app/views/demos/edit.html.erb
<section class="main_section">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-12 col-md-5">
				<h4 class="mb-5">Edit Demo</h4>
                <%= render 'form', demo: @demo %>
			</div>
		</div>
	</div>
</section>

app/views/demos/index.html.erb
<% if false %>
  <p id="notice"><%= notice %></p>
  <%= link_to 'New Demo', new_demo_path %>
  <%= link_to 'Settings', demo_settings_path %>
  <br>
  <br>

  <div class="container-fluid">
    <div class="row">
      <div class="col-2">
        <% @next_four_days.each do |datetime, appointment| %>
          <% if appointment.present? %>
            <span><%= date_translation datetime %>:</span>
            <br>
            <% appointment.each do |apt| %>
              <div>
                <%= link_to  demo_path(apt),{remote: true,'data-bs-toggle' => "modal", 'data-bs-target' => "#demo-modal", class: 'btn'} do  %>
                  Demo With <%= "#{apt.lead.first_name} #{apt.start_time.strftime('%l:%M %P')}"%>
                <%end%>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div class="col-10">
        <%= month_calendar(events: @appointments, attribute: :start_time) do |date, appointments| %>
          <%= date.day %>
          <% appointments.each do |apt| %>
            <div>
              <%= link_to  demo_path(apt),{remote: true,'data-bs-toggle' => "modal", 'data-bs-target' => "#demo-modal", class: 'btn'} do  %>
                <%= apt.duration%>
              <%end%>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="modal fade" id="demo-modal" tabindex="-1" role="dialog" aria-labelledby="demo-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div id="demo-show"></div>
    </div>
  </div>
<% end %>

<section class="main_section calendar-main-sec">
		<div class="container">
			<div class="row justify-content-center">
        <%= month_calendar(events: @appointments, attribute: :start_time) do |date, appointments| %>
          <%= date %>
        <% end %>
			</div>
		</div>
	</section>

	<!-- Modal -->
<div class="modal fade calendar-modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog h-100 d-flex justify-content-center align-items-center" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <%= image_tag("cross.png", alt: "#") %>
        </button>
      </div>
      <div class="modal-body">
	    <h1>Demo on Tuesday June 16, 2021</h1>
	    <h5>with Jack</h5>
        <a href="#"><button type="button">Send Demo Link Again</button></a>
      </div>
    </div>
  </div>
</div>

app/views/demos/new.html.erb
<section class="main_section">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-12 col-md-5">
				<h4 class="mb-5">New Demo</h4>
                <%= render 'form', demo: @demo %>
			</div>
		</div>
	</div>
</section>

app/views/demos/settings.html.erb
<section class="main_section calendar-set-sec">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-12 col-md-12">
        <%= simple_form_for current_user, url: user_path(current_user), method: :put, html: { class: "row justify-content-center calendar-set-head" } do |f| %>
					<div class="col-12 d-flex justify-content-between align-items-center p-0">
						<h4>
							<%= link_to demos_path do %>
								<%= image_tag('back-icon.png', alt: "#") %>
							<% end %>

							Calendar Settings
						</h4>
					</div>
					<div class="col-12">
						<h4>Zoom Demo Link</h4>
					</div>
					<div class="col-12 p-0">
						<div class="input-group">
              <%= f.input :zoom_link, label: false, placeholder: "Enter your personal meeting zoom link", input_html: { type: 'url' }, wrapper: false, required: true %>
						</div>
					</div>
					<div class="form-actions text-center">
						<button type="submit" class="btn_red"><span>Update Zoom Link</span></button>
					</div>
					<div class="col-12">
						<h4>Account Phone Number</h4>
					</div>
					<div class="col-12 p-0">
						<div class="input-group">
              <%= f.input :phone_number, label: false, placeholder: "Enter your personal phone number", wrapper: false, required: true, readonly: true %>
						</div>
					</div>
					<div class="col-12">
						<h4>Twilio Number</h4>
					</div>
					<div class="col-12 p-0">
						<div class="input-group">
              				<%= f.input :twilio_number, label: false, placeholder: "twilio number", wrapper: false, required: false, readonly: true %>
						</div>
					</div>
					<div class="col-12">
						<h4>Landing Page Link</h4>
					</div>
					<div class="col-12 p-0">
						<div class="input-group">
              <%= f.input :domain, label: false, placeholder: "Enter your personal landing page link", wrapper: false, required: true, readonly: true %>
						</div>
					</div>
					<% if @lead.present? %>
					<div class="col-12">
						<h4>Landing Page Link</h4>
					</div>
					<div class="col-12 p-0">
						<div class="input-group">
							<input type="text" name="" value="<%= "#{request. protocol}#{request. host_with_port}" %>/users/<%= current_user.id %>" readonly="readonly">
						</div>
					</div>
					<div class="col-12">
						<h4>Prospect Page Link</h4>
					</div>
					<div class="col-12 p-0">
						<div class="input-group">
							<input type="text" name="" value="<%= "#{request. protocol}#{request. host_with_port}" %>/users/<%= current_user.id %>/prospect/<%= @lead.phone_number %>" readonly="readonly">
						</div>
					</div>
					<div class="col-12">
						<h4>Contacted Page Link</h4>
					</div>
					<div class="col-12 p-0">
						<div class="input-group">
							<input type="text" name="" value="<%= "#{request. protocol}#{request. host_with_port}" %>/users/<%= current_user.id %>/contacted/<%= @lead.phone_number %>" readonly="readonly">
						</div>
					</div>
					<div class="col-12">
						<h4>Demo Page Link</h4>
					</div>
					<div class="col-12 p-0">
						<div class="input-group">
							<input type="text" name="" value="<%= "#{request. protocol}#{request. host_with_port}" %>/users/<%= current_user.id %>/demo/<%= @lead.phone_number %>" readonly="readonly">
						</div>
					</div>
					<div class="col-12">
						<h4>Followup Page Link</h4>
					</div>
					<div class="col-12 p-0">
						<div class="input-group">
							<input type="text" name="" value="<%= "#{request. protocol}#{request. host_with_port}" %>/users/<%= current_user.id %>/followup/<%= @lead.phone_number %>" readonly="readonly">
						</div>
					</div>
					<div class="col-12">
						<h4>Closing Page Link</h4>
					</div>
					<div class="col-12 p-0">
						<div class="input-group">
							<input type="text" name="" value="<%= "#{request. protocol}#{request. host_with_port}" %>/users/<%= current_user.id %>/closed/<%= @lead.phone_number %>" readonly="readonly">
						</div>
					</div>
					<% end %>
					<div class="col-12">
						<h4>Personal Sign Up Link</h4>
					</div>
					<div class="col-12 p-0">
						<div class="input-group">
							<input type="text" name="" value="http://nowkingdom.com/users/sign_up?at=<%= current_user.affiliate_token %>" readonly="readonly">
						</div>
					</div>
        <% end %>
        <%= simple_form_for Availability.new, html: { class: "row justify-content-center calendar-set-head" } do |f| %>

          <% if @availabilities.present? %>
            <div class="col-12">
              <h4>Availability</h4>
              <% @availabilities.each do |availability| %>
                <p>
                  <%= availability.duration %>
                  <%= link_to availability, method: :delete, data: { confirm: 'Are you sure?', remote: true } do %>
                    <%= image_tag('minus.png', alt: "#") %>
                  <% end %>
                </p>
              <% end %>
            </div>
          <% end %>

					<div class="col-12">
						<h4>Standard Work Hours</h4>
					</div>
					<div class="col-12 p-0">
						<div class="input-group d-flex justify-content-between">
              <%= f.input :start_time, collection: time_range, prompt: 'Select Start Time', label: false, wrapper: false %>
              <%= f.input :end_time, collection: time_range, prompt: 'Select End Time', label: false, wrapper: false %>
						</div>
					</div>
					<div class="col-12">
						<h4>Day of the Week</h4>
					</div>
					<div class="col-12 p-0">
						<div class="input-group d-flex">
							<%= f.input :day_of_week, collection: Date::DAYNAMES, prompt: 'Select Work Day', label: false, wrapper: false %>
						</div>
					</div>
					<div class="col-12 p-0">
						<button type="submit"><%= image_tag('plus1.png', alt: "#") %> Add</button>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</section>

app/views/demos/show.js.erb
$('#demo-show').html("<%= j render 'demo', appointment: @appointment %>");