config/routes.rb
Rails.application.routes.draw do
  get 'users/prospect'
  get 'users/contacted'
  # users
  resources :users, only: [:update]
  # demos
  resources :demos do
    post :send_reminder
  end
  get '/settings', to: 'demos#settings', as: 'demo_settings'
  # availabilities
  resources :availabilities
  # leads
  resources :leads do
    member do
      patch :change_stage
      post :closed_stage
    end

    collection do
      get :new_csv
      get :new_leads
    end
  end
  get '/lead_view', to: 'leads#lead_view', as: 'lead_view'
  get '/pipeline_view', to: 'leads#pipeline_view', as: 'pipeline_view'
  # users
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords' }

  get '/confirm_phone', to: 'static#confirm_phone', as: :confirm_phone
  post '/verify_otp', to: 'static#verify_otp', as: :verify_otp
  get '/after_sign_up', to: 'static#after_sign_up', as: :after_sign_up
  get "/generate_report", to: 'static#generate_report'
  post '/add_lead', to: 'static#add_lead', as: :web_add_lead
  get '/add_domain', to: "subscriptions#add_domain"
  post '/select_domain', to: "subscriptions#select_domain"
  post '/search_domain', to: "subscriptions#search_domain"

  get 'users/:id/prospect/:lead_number', to: 'users#prospect', as: :lead_prospect
  get 'users/:id/contacted/:lead_number', to: 'users#contacted', as: :lead_contacted
  get 'users/:id/demo/:lead_number', to: 'users#demo', as: :lead_demo
  get 'users/:id/followup/:lead_number', to: 'users#followup', as: :lead_followup
  get 'users/:id/closed/:lead_number', to: 'users#closed', as: :lead_closed
  get 'users/:id/change_stage/:lead_number', to: 'users#change_stage', as: :lead_change_stage
  post '/book_demo', to:'users#book_demo'
  get '/book_new', to:'users#book_new'

  get '/pay', to: 'static#pay'

  # registrations
  devise_scope :user do
    get 'registrations/new_subscription'
    get 'registrations/add_domain'
    get 'registrations/add_leads'
    post 'registrations/select_domain'
    post 'registrations/search_domain'
  end

  # CSV import route
  post 'leads/import', to: 'leads#import'

  resources :appointments do
   collection { get :day_view }
 end

  resources :subscriptions
  get 'users/:id', to: "static#user_template"
  
  # home page
  root 'static#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lead.rb
# frozen_string_literal: true

class Lead < ApplicationRecord
  include Rails.application.routes.url_helpers
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :demos, dependent: :destroy
  enum stage: { prospecting: 0, contacted: 1, demo: 2, followup: 3, closing: 4 }
  enum heat: { cold: 0, warm: 1, hot: 2 }

  validates :first_name, presence: true
  validates :phone_number, uniqueness: true,
                           presence: true
  #  This validation for US numbers
  validates :phone_number,
            format: { with: /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/,
                      message: 'Invalid phone number' }

  scope :search, ->(query) { where('first_name ILIKE ? OR last_name ILIKE ?', "%#{query}%", "%#{query}%") }
  scope :search_stage, ->(query) { where(stage: query) }

  after_create :after_lead_create

  require 'csv'

  # user should be deleted after adding the functionality for user to sign-in
  def self.import(user, path)
    leads_hash = []
    CSV.foreach(path, headers: true,
                      skip_blanks: true,
                      skip_lines: /^(?:,\s*)+$/) do |row|
      new_hash = {}
      row.to_hash.each_pair do |k, v|
        new_hash.merge!({ k.downcase => v })
        next if new_hash['phone_number'].nil?
      end
      lead = user.leads.create(new_hash)
      if lead.id
        lead = where('phone_number = ?', new_hash['phone_number']).first
        leads_hash << lead
      end
    end
    leads_hash
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def after_lead_create
    self.update(stage: "prospecting")
    send_satge_related_notification
  end

  def send_satge_related_notification
    message = ""
    message2 = ""
    is_send = false
    case stage
    when "prospecting"
      message = get_send_message(prospecting_message_send_at)
    when "contacted"
      message = get_send_message(contacted_message_send_at)
    when "demo"
      message = get_send_message(demo_message_send_at)
      message2 = get_send_message(followup_message_send_at, 'demo_msg2')
    when "followup"
      message = get_send_message(followup_message_send_at)
    when "closing"
      message = get_send_message(closing_message_send_at)
    end
    p "send msg to lead #{self.stage}"
    p message
    p message2
    is_send = send_text(user.phone_number, message) if message.present?
    send_text(user.phone_number, message2) if message2.present?
    update_send_at if is_send.present?
  end

  def send_text(phone_number,message)
    begin
      TwilioClient.new.user_sms_to_lead(self, message)
      return true
    rescue Exception => e
      return true
    end
  end

  def send_lead(phone_number,message, filePath)
    begin
      TwilioClient.new.send_lead(self, message, filePath)
      return true
    rescue Exception => e
      return true
    end
  end

  def send_demo_nofication
    send_text(phone_number,"Demo created successfuly, you will be notified with Meeting link")
  end

  def send_document_nofication(filePath)
    send_lead(phone_number,"Document will be shared later. http://3.84.239.72/DeusBlueprint.pdf ", filePath)
  end

  def update_send_at
    case stage
    when "prospecting"
      self.update_attribute(:prospecting_message_send_at, Time.now)
    when "contacted"
      self.update_attribute(:contacted_message_send_at, Time.now)
    when "demo"
      self.update_attribute(:demo_message_send_at, Time.now)
    when "followup"
      self.update_attribute(:followup_message_send_at, Time.now)
    when "closing"
      self.update_attribute(:closing_message_send_at, Time.now)
    end
  end

  def get_send_message(is_send_at, demo_msg=nil)
    return if is_send_at.present?
    if stage == "prospecting"
      if added_from == "web_form"
        msg = " Look at these modern ways to make that much needed Passive Income #{get_doc_url} " + "Talk soon, " + "#{user.try(:full_name)}"
      else
        msg = "Hey #{first_name}, " + " What would you do if you woke up and didn’t have anything but the clothes on your back and the phone in your hand? That’s a tough one huh? Clink the link #{get_stage_url} and we’ll show how you can go from broke to whatever you can think of. " + "#{user.try(:full_name)}"
      end
    elsif stage == "contacted"
      msg = "Hey #{first_name}, " + " It doesn’t matter what road you are on right now. You can always change directions and start making more money. Go to the link  #{get_stage_url}  to find out how to invest in yourself." + "It’s your time to win, " + "#{user.try(:full_name)}"
    elsif stage == "demo"
      if demo_msg == "demo_msg2"
        # msg = msg + " your meeting is coming up at #{demo_scheduled_time} and we are going to discuss at Zoom #{user.zoom_link}"
        msg = "Hi #{first_name}, " + " Here’s the link for your demo #{user.zoom_link}. You’re going to love to hear about this! " + "#{user.try(:full_name)}"
      else
        msg = "Yayyy #{first_name}, " + "You booked a demo! You’re headed in the right direction. If they can do it so can you! See who went from Rags to Riches at this link #{get_stage_url}. " + "#{user.try(:full_name)}"
      end
    elsif stage == "followup"
     msg = "Hey #{first_name}, " + " Do you know the difference between highly successful and non successful ppl?  Successful ppl don’t allow their fears to stop them from making smart decisions. The smartest decision is here #{get_stage_url} " + "Don’t let this opportunity slip through your fingers. " + "#{user.try(:full_name)}"
    elsif stage == "closing"
      msg = "Yaass #{first_name}, " + " Can’t you just feel the good vibes and energy going through your body? Watch the video we made just to celebrate you #{get_stage_url} " + "#{user.try(:full_name)}"
    end
    # "#{stage.to_s.titleize}: #{get_stage_url} #{zoom_link if stage == 'demo'}" unless is_send_at.present?
    return msg
  end

  def demo_scheduled_time
    schedule = appointments.last
    if schedule
      "#{schedule.start_time.strftime("%F %I:%M %p")} - #{schedule.end_time.strftime("%F %I:%M %p")}"
    end
  end

  def zoom_link
    "\nZoom Link: #{user.zoom_link}"
  end

  def get_doc_url
    "#{Rails.application.credentials.base_url}/DeusBlueprint.pdf"
  end

  def get_stage_url
    state_name_in_url = stage
    if stage === "prospecting"
      state_name_in_url = "prospect"
    elsif stage === "closing"
      state_name_in_url = "closed"
    end
    "#{Rails.application.credentials.base_url}/users/#{user.try(:id)}/#{state_name_in_url}/#{phone_number}"
  end
  

  def self.check_pending_prospecting
    pipeline_waiting_hour = Rails.application.credentials.pipeline_waiting_hour
    limit_hours = Rails.env == "production" ? pipeline_waiting_hour.hours : 12.minutes
    prospectings = Lead.search_stage("prospecting").where("prospecting_message_send_at < ?",(Time.now - limit_hours).in_time_zone('UTC'))
    p "Checking Leads - Prospect - at #{Time.now}"
    p "Leads - Prospect - count: #{prospectings.size}"
    prospectings.each do |prospecting|
      unless prospecting.appointments.count.positive?
        prospecting.update_attribute(:stage, 1)
        prospecting.send_satge_related_notification
      end
    end
  end

  def self.check_pending_demo
    pipeline_waiting_hour = Rails.application.credentials.pipeline_waiting_hour
    limit_hours = Rails.env == "production" ? pipeline_waiting_hour.hours : 12.minutes
    demos = Lead.search_stage("demo").where("demo_message_send_at < ?",(Time.now - limit_hours).in_time_zone('UTC'))
    p "Checking Leads - Demo - at #{Time.now}"
    p "Leads - Demo - count: #{demos.size}"
    demos.each do |demo|
      unless demo.is_purchase_subscription.present?
        demo.update_attribute(:stage, 3)
        demo.send_satge_related_notification
      end
    end
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  include Pagy::Backend
  before_action :user_authenticated?
  before_action :set_lead, only: %i[show edit update change_stage destroy]
  before_action :set_leads, only: %i[pipeline_view]

  def index
    # chechk the type of params for search bar and return the correct query result, check private methods
    get_leads

    respond_to do |format|
       format.html
       format.json { render json: { html: render_to_string(partial: 'leads/leads.html.erb') }}
    end

  end

  # GET /lead_view
  def lead_view
    get_lead_view
  end

  def get_lead_view
    @stage = 'prospecting'
    @keyword = ''
    if params[:stage]
      @stage = params[:stage]
    end
    if params[:name]
      @pagy, @leads = pagy(Lead.where(first_name: params[:name], stage: @stage), page: params[:page], items: 5)
    else
      @pagy, @leads = pagy(Lead.where(stage: @stage))
    end
    if @leads.first
      @lead = @leads.first
    else
      @lead = Lead.last
    end
    puts @pagy
  end

  # GET /pipeline_view
  def pipeline_view
    @leads = Lead.search(params[:query]) if params[:query]
  end

  # GET /leads/new
  def new
    @lead = Lead.new
    p @lead
  end

  # GET /leads/1/edit
  def edit; end

  # POST /leads or /leads.json
  def create
    @lead = current_user.leads.create(lead_params)
    respond_to do |format|
      if @lead.save
        format.html { redirect_to leads_url, notice: 'Lead was successfully created.' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render js: @lead.errors, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def import
    # @current_user should be deleted after adding the functionality for user to sign-in

    @leads = Lead.import(current_user, params[:file])
    respond_to do |format|
      if @leads
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1 or /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to leads_url, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.js
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  def change_stage
    @lead.update(stage: params[:lead][:stage].to_s) if params.dig(:lead, :stage)
  end

  def closed_stage
    @lead.update(stage: 4)
    @lead.send_satge_related_notification
    redirect_to leads_path
  end

  # DELETE /leads/1 or /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lead
    @lead = Lead.find(params[:id])
  end

  def set_leads
    @leads = Lead.all
  end

  # Only allow a list of trusted parameters through.
  def lead_params
    params.require(:lead).permit(:first_name, :phone_number, :last_name, :facebook, :instagram, :linkedin)
  end

  # get the type of the input field for the searh bar and return the correct query result
  def get_leads
    if params[:number]
      @pagy, @leads = pagy(current_user.leads.where(phone_number: params[:number]))
    elsif params[:name]
      @pagy, @leads = pagy(current_user.leads.where(first_name: params[:name]))
    elsif params[:stage]
      @pagy, @leads = pagy(current_user.leads.where(stage: params[:stage]))
    elsif params[:default]
      @pagy, @leads = pagy(current_user.leads)
    else
      @pagy, @leads = pagy(current_user.leads)
    end
  end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/_csv.html.erb
<% if false %>
  <% @leads.each do |l| %>
    <tr class="contactItem">
      <td><%= l.first_name %></td>
      <td><%= l.phone_number %></td>
      <td><%= l.stage %></td>
      <td>
        <%= link_to "Edit", edit_lead_path(l.id), {remote: true, 'data-bs-toggle' => "modal", 'data-bs-target' => "#exampleModalToggle", class: 'btn btn-primary btn'}  %>
      </td>
      <td>
        <%= link_to "Delete", lead_path(l.id), class: 'btn btn-danger btn', method: :delete %>
        <% if l.stage == 'demo' %>
          <span style="color: white;"><%= "#{Rails.application.credentials.base_url}/users/sign_up?at=#{l.user.affiliate_token}&number=#{l.phone_number}" %></span>
        <% end %>
      </td>
    </tr>
  <% end %>
<% end %>

<% @leads.each do |l| %>
  <div class="bot_row">
    <div class="td"><%= l.first_name %></div>
    <div class="td"><a href="#"><%= image_tag("phone-icon.svg", alt: "#") %> <%= l.phone_number %><a href="#"></a></div>
    <div class="td">
      <ul class="list-inline">
        <li class="list-inline-item">
          <%= link_to edit_lead_path(l.id), class: 'btn_tab' do %>
            <%= image_tag("edit-button-icon.svg", alt: "#") %> Edit
          <% end %>
        </li>
        <li class="list-inline-item">
          <%= link_to lead_path(l.id), class: 'btn_tab', method: :delete do %>
            <%= image_tag("remove-button-icon.svg", alt: "#") %> Remove
          <% end %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

<div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggle" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

      <div id="modal-content-edit">

      </div>
    </div>
  </div>
</div>

app/views/leads/_edit.html.erb
  <div class="modal-header">
    <h5 class="modal-title" id="modalToggleLabelEdit">Edit Lead</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <%= render 'form' %>
  </div>
  

app/views/leads/_mobile_csv.html.erb
<% @leads.each do |l| %>
    <div class="tab_flex">
      <div>
        <div class="td"><%= l.first_name %></div>
        <div class="td"><a href="#"><%= image_tag("phone-icon.svg", alt: "#") %> <%= l.phone_number %></a></div>
      </div>
      <div>
        <ul class="list-inline">
          <li class="list-inline-item">
            <%= link_to edit_lead_path(l.id), class: 'btn_tab' do %>
              <%= image_tag("edit-button-icon.svg", alt: "#") %>
            <% end %>
          </li>
          <li class="list-inline-item">
            <%= link_to lead_path(l.id), class: 'btn_tab', method: :delete do %>
              <%= image_tag("remove-button-icon.svg", alt: "#") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
  
  <div class="modal fade" id="exampleModalToggleMobile" aria-hidden="true" aria-labelledby="exampleModalToggle" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
  
        <div id="modal-content-edit">
  
        </div>
      </div>
    </div>
  </div>
  

app/views/leads/_new.html.erb
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalToggleLabelNew">Add Leads</h5>
    <a class="m-2" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal" data-bs-dismiss="modal">Import CSV</a>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>

  <div class="modal-body">
    <%= render 'form' %>
  </div>

app/views/leads/create.js.erb
$(".notice").remove();

<% @lead.errors.full_messages.each do |msg| %>
$("#helpBlock").append(`<div class="notice"><%= escape_javascript(msg)%></div>`);
<% end %>

app/views/leads/import.js.erb
$('.main_section').html("<%= j render 'new_leads', leads: @leads %>");

app/views/leads/index.html.erb
<section class="main_section">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-12 col-md-8">
				<h4>Add Leads</h4>
				<p>Don’t worry. You can add more later.</p>
				<div class="hidden-xs">
					<div class="table_box">
						<div class="top_head">
							<div class="th">Name</div>
							<div class="th">Phone</div>
							<div class="th">Actions
								<div class="dropdown">
								  <button class="dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
								    <%= image_tag("three_dots.png", alt: "#") %>
								  </button>
								  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
								    <li><a class="dropdown-item" href="#">Action</a></li>
								    <li><a class="dropdown-item" href="#">Another action</a></li>
								    <li><a class="dropdown-item" href="#">Something else here</a></li>
								  </ul>
								</div>
							</div>
						</div>
						<div id="leads-container" class="bot_data">
              				<%= render 'leads' , remote: true %>
						</div>
					</div>
				</div>
				<div class="visible-xs">
					<div class="table_mob">
						<div class="dropdown">
						  <button class="btn_drop dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
						    Sort by Name <%= image_tag("dropdown-icon.svg", alt: "#") %>
						  </button>
						  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
						    <li><a class="dropdown-item" href="#">Sort by Name</a></li>
						    <li><a class="dropdown-item" href="#">Sort by Name</a></li>
						    <li><a class="dropdown-item" href="#">Sort by Name</a></li>
						  </ul>
						</div>
						<div id="leads-container">
						<%= render 'mobile_leads' , remote: true %>
						</div>
					</div>
				</div>
				<div class="text-right">
					<%= link_to new_lead_path, class: 'btn_red' do %>
						<span><%= image_tag("add-leads-button-icon.svg", alt: "#") %> Add Leads</span>
					<% end %>
					<button class="btn_purple"><span>Finish</span></button>
				</div>
			</div>
		</div>
	</div>
</section>

<div class="modal fade" id="exampleModalToggleNew" aria-hidden="true" aria-labelledby="exampleModalToggleLabelNew" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalToggleLabel2">Import CSV</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: leads_import_path, local: false  do |form|%>
          <%= form.file_field :file %>
          <%= submit_tag "Import" %>
          <span id="something" class="help-block"></span>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= link_to 'Finish', leads_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'leads' %>

app/views/leads/lead_view.html.erb
<section class="main_section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-12 col-md-12">
					<ul class="list-inline main_view">
						<li class="list-inline-item"><a href="" class="btn_red active"><span>Lead View</span></a></li>
						<li class="list-inline-item"><a href="/pipeline_view" class="btn_purple"><span>Pipeline View</span></a></li>
					</ul>
					<div class="lead_view_flex">
						<h4><%= @lead.first_name %></h4>
						<div class="tager text-uppercase"><%= @lead.heat ? @lead.heat : 'cold' %></div>
						<select class="form-control">
							<option>PROSPECTING</option>
							<option>Contacted</option>
							<option>Demo</option>
							<option>Followup</option>
							<option>Close</option>
						</select>
						<%= link_to edit_lead_path(@lead.id), class: "edit" do %>
						<%= image_tag("edit-icon-2.svg", alt: "#") %>
						<% end %>
					</div>
					<div class="row justify-content-center">
						<div class="col-12 col-md-4">
							<div class="blue_box">
								<div class="search_flex">
									<div class="form-group group_lg">
										<input type="text" name="" class="search form-control" placeholder="Search">
										<span class="search_icon"><%= image_tag("search-icon.svg", alt: "#") %></span>
									</div>
									<div class="form-group">
										<button class="add_button"><%= image_tag("plus-button-icon.svg", alt: "#") %></button>
									</div>
								</div>
								<div class="search_flex">
									<div class="form-group">
										<select class="form-control">
											<option>Filter</option>
											<option>Filter</option>
											<option>Filter</option>
										</select>
									</div>
								</div>
                				<% @leads.each do |lead| %>
                  					<div class="dark_box">
                    					<%= image_tag("profile-image-3.png", alt: "#") %>
  										<div class="text">
  											<div class="name">
                        						<%= lead.full_name %>
                        						<% if lead.heat == "warm" %>
                          							<span class="type yellow">WARM</span>
                        						<% elsif lead.heat == "hot" %>
                          							<span class="type red">HOT</span>
                        						<% else %>
                          							<span class="type blue">COLD</span>
                        						<% end %>
                      						</div>
  											<a href="#" class="tele"><%= lead.phone_number %></a>
  											<div class="dropdown">
  										  		<button class="dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                          							<%= image_tag("three_dots2.png", alt: "#") %>
  										  		</button>
												<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
													<li><a class="dropdown-item" href="#">Action</a></li>
													<li><a class="dropdown-item" href="#">Another action</a></li>
													<li><a class="dropdown-item" href="#">Something else here</a></li>
												</ul>
											</div>
										</div>
										<span class="unread"></span>
									</div>
                				<% end %>
								<%= pagy_nav(@pagy) %>
								<ul class="list-inline controls">
									<li class="list-inline-item"><a href="#"><%= image_tag("previous-button.png", alt: "#") %></a></li>
									<li class="list-inline-item"><a href="#"><%= image_tag("next-button.png", alt: "#") %></a></li>
								</ul>
							</div>
						</div>
						<div class="col-12 col-md-6">
							<div class="blue_box">
								<div class="message_wrap">
									<div class="messenger left">
                    					<%= image_tag("profile-image-2.png", alt: "#") %>
										<div class="text_box">Hey Ivone, this is Peter from Harty Builders. Did you descide on which product you wanted yet?</div>
										<span class="time">Peter on May 15th, 2021 @ 9:37 am</span>
									</div>
									<div class="messenger right">
                    					<%= image_tag("profile-image-3.png", alt: "#") %>
										<div class="text_box">Not yet.. Still trying to figure out what I want. <br>Any recommendations?</div>
										<span class="time">Ivone May 15th, 2021 @ 9:37 am</span>
									</div>
									<div class="messenger left">
                    					<%= image_tag("profile-image-2.png", alt: "#") %>
										<div class="text_box">Hey Ivone, this is Peter from Harty Builders. Did you descide on which product you wanted yet?</div>
										<span class="time">Peter on May 15th, 2021 @ 9:37 am</span>
									</div>
								</div>
								<div class="message_write">
									<input type="text" placeholder="Type your message..." class="form-control">
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

app/views/leads/new.html.erb
<section class="main_section">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-12 col-md-5">
        <div class="row">
					<div class="col-6">
						<h4 class="mb-5">New Leads</h4>
					</div>
					<div class="col-6">
						<ul class="list-inline top_select">
							<li class="list-inline-item"><a href="" class="active">One Person</a></li>
							<li class="list-inline-item"><a href="/leads/new_csv" class="">CSV Upload</a></li>
						</ul>
					</div>
				</div>
        <%= render 'form' %>
			</div>
		</div>
	</div>
</section>

app/views/leads/new.js.erb
$("#exampleModalToggleNew").find(".modal-content").html("<%= j render 'leads/new' %>")
$("#exampleModalToggleNew").modal('show')

app/views/leads/new_csv.html.erb
<section class="main_section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-12 col-md-5">
					<div class="row">
						<div class="col-6">
							<h4 class="mb-5">New Leads</h4>
						</div>
						<div class="col-6">
							<ul class="list-inline top_select">
								<li class="list-inline-item"><a href="/leads/new">One Person</a></li>
								<li class="list-inline-item"><a href="#" class="active">CSV Upload</a></li>
							</ul>
						</div>
					</div>
					
					<%= form_with url: leads_import_path, class: 'text-center', local: false  do |form|%>
						<%= image_tag("document-icon.svg", alt: "#", class: "document") %>
						<div class="upload-btn-wrapper">
						  	<button class="btn_purple"><span><%= image_tag("add-leads-button-icon.svg", alt: "#") %> Upload CSV</span></button>
						  	<%= form.file_field :file %>
						</div>
						<p>The CSV should be formatted to have a <br>“name” and “number” column</p>
						<div class="text-center mt-5">
							<a href="/leads" class="btn_red btn_red2 me-2"><span>Cancel</span></a>
							<button type="submit" class="btn_red"><span>Import</span></a>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</section>