config/routes.rb
Rails.application.routes.draw do
  get 'users/prospect'
  get 'users/contacted'
  # users
  resources :users, only: [:update]
  # demos
  resources :demos do
    post :send_reminder
  end
  get '/settings', to: 'demos#settings', as: 'demo_settings'
  # availabilities
  resources :availabilities
  # leads
  resources :leads do
    member do
      patch :change_stage
      post :closed_stage
    end

    collection do
      get :new_csv
      get :new_leads
    end
  end
  get '/lead_view', to: 'leads#lead_view', as: 'lead_view'
  get '/pipeline_view', to: 'leads#pipeline_view', as: 'pipeline_view'
  # users
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords' }

  get '/confirm_phone', to: 'static#confirm_phone', as: :confirm_phone
  post '/verify_otp', to: 'static#verify_otp', as: :verify_otp
  get '/after_sign_up', to: 'static#after_sign_up', as: :after_sign_up
  get "/generate_report", to: 'static#generate_report'
  post '/add_lead', to: 'static#add_lead', as: :web_add_lead
  get '/add_domain', to: "subscriptions#add_domain"
  post '/select_domain', to: "subscriptions#select_domain"
  post '/search_domain', to: "subscriptions#search_domain"

  get 'users/:id/prospect/:lead_number', to: 'users#prospect', as: :lead_prospect
  get 'users/:id/contacted/:lead_number', to: 'users#contacted', as: :lead_contacted
  get 'users/:id/demo/:lead_number', to: 'users#demo', as: :lead_demo
  get 'users/:id/followup/:lead_number', to: 'users#followup', as: :lead_followup
  get 'users/:id/closed/:lead_number', to: 'users#closed', as: :lead_closed
  get 'users/:id/change_stage/:lead_number', to: 'users#change_stage', as: :lead_change_stage
  post '/book_demo', to:'users#book_demo'
  get '/book_new', to:'users#book_new'

  get '/pay', to: 'static#pay'

  # registrations
  devise_scope :user do
    get 'registrations/new_subscription'
    get 'registrations/add_domain'
    get 'registrations/add_leads'
    post 'registrations/select_domain'
    post 'registrations/search_domain'
  end

  # CSV import route
  post 'leads/import', to: 'leads#import'

  resources :appointments do
   collection { get :day_view }
 end

  resources :subscriptions
  get 'users/:id', to: "static#user_template"
  
  # home page
  root 'static#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
# frozen_string_literal: true

# Appointment model
class Appointment < ApplicationRecord
    include ActionView::Helpers::DateHelper
  
    validates :start_time, :end_time, presence: true
  
    belongs_to :user
    belongs_to :lead
    belongs_to :assigned_to, class_name: 'User', foreign_key: :assigned_to_id
  
    # Scopes
    scope :starts_from, lambda { |start_time, user|
      where(user_id: user.id, start_time: start_time.beginning_of_month.beginning_of_week..start_time.end_of_month.end_of_week)
    }
    scope :of_day, lambda { |datetime, user|
      where(user_id: user.id, start_time: datetime.beginning_of_day..datetime.end_of_day)
        .or(where(user_id: user.id, end_time: datetime.beginning_of_day..datetime.end_of_day))
        .group_by_hour_of_day(series: true, format: '%l:%M %p') { |u| u.start_time }
    }

    scope :month, lambda { |month|
      where(start_time: month.beginning_of_month.beginning_of_week..month.end_of_month.end_of_week)
    }

    scope :next_four_days, lambda { |datetime|
      where(start_time: datetime.beginning_of_day..(datetime + 3.days).end_of_day)
        .group_by(&:start_time)
    }

  
    validate :check_valid_time, on: :create
    enum progress: %i[SCHEDULED OTW START END INVOICE PAID]
    after_create :lead_stage_moved_to_demo

    def lead_stage_moved_to_demo
      lead.update_attribute(:stage, 'demo')
      lead.send_satge_related_notification
    end
  
    # Utility Methods
    def self.employee_only(assigned_to)
      where(assigned_to: assigned_to)
    end
  
    # Instance Methods
    def completes_on_same_day?
      start_time.to_date == end_time.to_date
    end
    
    def availabilities
      user.availabilities
    end

    def duration
      "#{start_time.strftime('%l:%M %P')} - #{end_time.strftime('%l:%M %P')}"
    end

    def end_time
      start_time + 30.minutes
    end
  
    def check_valid_time
      # check validation start and end time's conflict and availables
      appointments = collect_exits_appointments
      if appointments.count.positive?
        if appointments.size == 1 
          if appointments.first.id
            errors.add('Time conflicting', 'with existing time.')
          end
        else
          errors.add('Time conflicting', 'with existing time.')
        end
      else
        select_availabilities = selected_availabilities
        # errors.add('Invalid', 'start and end time.') unless select_availabilities.count.positive?
      end
    end
  
    def collect_exits_appointments
      assigned_to.appointments.where.not(id: id).where('start_time <= ? AND end_time >= ?', start_time, end_time)
    end
  
    def selected_availabilities
      availabilities.where('day_of_week = ? AND (start_time::time <= ? AND end_time::time >= ?)',
                           start_time.strftime('%A'), start_time.strftime('%r'), end_time.strftime('%r'))
    end
  
    def future_formatting_date
      "#{start_time.strftime('%D')} #{start_time.strftime('%r')} #{end_time.strftime('%r')}"
    end
  
    # formats appointment date based on start date
    def time_format_from
      if Time.now < start_time
        "#{distance_of_time_in_words_to_now(start_time)} from now"
      else
        "#{distance_of_time_in_words_to_now(start_time)} ago"
      end
    end
  
    # sends text messages to the admin members of an account when progress status is updated
    def send_text_to_members(user)
      message = 'appointment hasa been scheduled'
      assignee = assigned_to.full_name
      service_name = service.name
      case progress
      when 'SCHEDULED'
        message = "appointment has been scheduled for #{service_name}"
      when 'OTW'
        message = "#{assignee} is on the way for the #{service_name} service"
      when 'START'
        message = "#{assignee} has started the appointment for the #{service_name} service"
      when 'END'
        message = "#{assignee} has completed the #{service_name} service"
      when 'INVOICE'
        message = "an invoice has been created for #{assignee} for the #{service_name} service"
      when 'PAID'
        message = "a payment has been made to #{assignee} for the #{service_name} service"
      else
        message
      end
  
        TwilioClient.new.send_text(user.phone_number, message)
    end
  end
  

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController # rubocop:todo Style/Documentation
    # before_action :authenticate_user!, except: %i[availabilitie_time]
    before_action :set_appointment, only: %i[show edit update destroy]
    before_action :set_availability, only: %i[create]
  
    def index
      start_date = params.fetch(:start_date, Date.today).to_date
      @appointments = Appointment.includes(:assigned_to).starts_from(start_date, current_user)
      
      @availabilities = current_user.availabilities.order('start_time asc')
      @availabilitie_times = Availability.inbetween_data(@availabilities)
    end
  
    def day_view
      @start_date = params.fetch(:date, Date.today).to_date
      @appointments = Appointment.includes(:assigned_to).of_day(@start_date, current_user)
    end
  
    # GET /appointments/1 or /appointments/1.json
    def show; end
  
    # GET /appointments/new
    def new; end
  
  
    # GET /appointments/1/edit
    def edit; end
  
    # POST /appointments or /appointments.json
    def create
      @appointment = Appointment.new(appointment_params)
      @appointment.progress = 1
      assign_member
      respond_to do |format|
        if @appointment.save
          @lead = @appointment.lead
          format.js 
        else
          p @appointment.errors
          format.js
        end
      end
    end
  
    def assign_member
      availability_info
      @appointment.assigned_to = @availability.user
      @appointment.start_time = "#{@available_date} #{
                                  @available_start_time}".to_datetime
      @appointment.end_time = "#{@available_date} #{
                                  @available_end_time}".to_datetime
    end
  
    def availability_info
      @available_date = params[:availability_id].split('^#^')[3]
      @available_start_time = params[:availability_id].split('^#^')[1]
      @available_end_time = params[:availability_id].split('^#^')[2]
    end
  
    # PATCH/PUT /appointments/1 or /appointments/1.json
    def update
      respond_to do |format|
        if @appointment.update(appointment_params)
          format.html do
            flash[:notice] = 'Appointment was successfully updated.'
            redirect_back(fallback_location: root_path)
          end
          format.json { render :show, status: :ok, location: @appointment }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @appointment.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def availabilitie_time
      @availabilities = Availability.service_employee_availabilities(@service).order('start_time asc')
      @availabilitie_times = Availability.inbetween_data(@availabilities, @service)
    end
  
    # updates appointment progress
    def update_appointment_progress
      @appointment_displayed_in_progress = Appointment.find_by(id: params[:appointment_id])
      @state = params[:state_number].to_i
      @appointment_displayed_in_progress.update(progress: @state)
      @appointment_displayed_in_progress.send_text_to_members(current_user)
  
      @invoice = Invoice.new
      @statuses = Invoice.new.all_statuses.to_a.map { |c| [c[1], c[0]] }
      @invoice_types = Invoice.new.all_invoice_types.to_a.map { |c| [c[1], c[0]] }
      @customer = @appointment_displayed_in_progress.customer
      respond_to do |format|
        format.js { render :update_appointment_progress }
      end
    end
  
    # get select-appointment/:id, ajax
    def select_appointment
      @appointment_displayed_in_progress = Appointment.find_by(id: params[:id])
      @customer = @appointment_displayed_in_progress.customer
      @invoice = Invoice.new
      @statuses = Invoice.new.all_statuses.to_a.map { |c| [c[1], c[0]] }
      @invoice_types = Invoice.new.all_invoice_types.to_a.map { |c| [c[1], c[0]] }
      respond_to do |format|
        format.js { render :update_appointment_progress }
      end
    end
  
    # DELETE /appointments/1 or /appointments/1.json
    def destroy
      @appointment.destroy
      respond_to do |format|
        format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find_by(id: params[:id])
    end
  
    def set_availability
      @availability = Availability.find_by(id: params[:availability_id].split('^#^')[0])
    end
  
    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:user_id, :lead_id, :start_time,:end_time)
                                          
    end
  end
  

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :lead_id %>
    <%= f.input :assigned_to_id %>
    <%= f.input :start_time %>
    <%= f.input :end_time %>
    <%= f.input :progress %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/appointments/create.js.erb
<% if @appointment.errors.any? %>
	$('.appointment_errors').html("<%= @appointment.errors.full_messages.join(',') %>");
<%else%>
	$('.appointment_errors').html("Appointment Successfully created!");
	$('#availability_form')[0].reset();
	$('#availability-picker').prop("selectedIndex",0)
<%end%>

setTimeout(function(){
   $("#book_demo .btn-close").click();
	// location.reload();
   $(window.location.replace("<%= lead_demo_path(@appointment.user_id, @lead.phone_number)%>"))
}, 1000);

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Lead</th>
      <th>Assigned to</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Progress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.user_id %></td>
        <td><%= appointment.lead_id %></td>
        <td><%= appointment.assigned_to_id %></td>
        <td><%= appointment.start_time %></td>
        <td><%= appointment.end_time %></td>
        <td><%= appointment.progress %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @appointment.user_id %>
</p>

<p>
  <strong>Lead:</strong>
  <%= @appointment.lead_id %>
</p>

<p>
  <strong>Assigned to:</strong>
  <%= @appointment.assigned_to_id %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @appointment.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @appointment.end_time %>
</p>

<p>
  <strong>Progress:</strong>
  <%= @appointment.progress %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>