config/routes.rb
Rails.application.routes.draw do
  get 'users/prospect'
  get 'users/contacted'
  # users
  resources :users, only: [:update]
  # demos
  resources :demos do
    post :send_reminder
  end
  get '/settings', to: 'demos#settings', as: 'demo_settings'
  # availabilities
  resources :availabilities
  # leads
  resources :leads do
    member do
      patch :change_stage
      post :closed_stage
    end

    collection do
      get :new_csv
      get :new_leads
    end
  end
  get '/lead_view', to: 'leads#lead_view', as: 'lead_view'
  get '/pipeline_view', to: 'leads#pipeline_view', as: 'pipeline_view'
  # users
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords' }

  get '/confirm_phone', to: 'static#confirm_phone', as: :confirm_phone
  post '/verify_otp', to: 'static#verify_otp', as: :verify_otp
  get '/after_sign_up', to: 'static#after_sign_up', as: :after_sign_up
  get "/generate_report", to: 'static#generate_report'
  post '/add_lead', to: 'static#add_lead', as: :web_add_lead
  get '/add_domain', to: "subscriptions#add_domain"
  post '/select_domain', to: "subscriptions#select_domain"
  post '/search_domain', to: "subscriptions#search_domain"

  get 'users/:id/prospect/:lead_number', to: 'users#prospect', as: :lead_prospect
  get 'users/:id/contacted/:lead_number', to: 'users#contacted', as: :lead_contacted
  get 'users/:id/demo/:lead_number', to: 'users#demo', as: :lead_demo
  get 'users/:id/followup/:lead_number', to: 'users#followup', as: :lead_followup
  get 'users/:id/closed/:lead_number', to: 'users#closed', as: :lead_closed
  get 'users/:id/change_stage/:lead_number', to: 'users#change_stage', as: :lead_change_stage
  post '/book_demo', to:'users#book_demo'
  get '/book_new', to:'users#book_new'

  get '/pay', to: 'static#pay'

  # registrations
  devise_scope :user do
    get 'registrations/new_subscription'
    get 'registrations/add_domain'
    get 'registrations/add_leads'
    post 'registrations/select_domain'
    post 'registrations/search_domain'
  end

  # CSV import route
  post 'leads/import', to: 'leads#import'

  resources :appointments do
   collection { get :day_view }
 end

  resources :subscriptions
  get 'users/:id', to: "static#user_template"
  
  # home page
  root 'static#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user

  validates :start_time, :end_time, :day_of_week, presence: true

  validate :check_time_conflicting
 
  # Checking new availability time conflicting with existing availability time
  def check_time_conflicting
    stime = start_time.strftime('%r')
    etime = end_time.strftime('%r')
    wday = day_of_week
    # Validating - Valid start and end time
    errors.add('Invalid', 'end time.') if valid_start_time

    # Validating - Conflicts with existing time
    conflicting_times = select_conflicting_times(stime, etime, wday)
    errors.add('Time conflicting', 'with existing time.') if conflicting_times.present?
  end

  def valid_start_time
    start_time >= end_time
  end

  def select_conflicting_times(stime, etime, wday)
    # rubocop:disable Layout/LineLength
    user.availabilities.where('day_of_week = ? AND ((start_time::time <= ? AND end_time::time >= ?) OR (start_time::time <= ? AND end_time::time >= ?) OR (start_time::time > ? AND end_time::time < ?))', wday, stime, stime, etime, etime, stime, etime)
    # rubocop:enable Layout/LineLength
  end

  def service_detail
    "#{start_time.strftime('%m/%d %I:%M %P')} - #{
      end_time.strftime('%I:%M %P')} with #{member.user.full_name}"
  end

  def self.float_to_time
    sec = ((0.5 || 1) * 3600).to_i
    min, sec = sec.divmod(60)
    hour, min = min.divmod(60)
    [hour, min, sec]
  end

  def self.inbetween_data(availabilities)
    data = []
    add_time = float_to_time
    (Date.tomorrow..Date.today + 4.day).each do |day|
      availabilities.where(day_of_week: day.strftime('%A')).each do |a|
        future_dates = a.collect_future_date_times
        stime = a.start_time
        (1..a.time_difference).each do |_time|
          next unless stime < a.end_time

          etime = stime + add_time[0].hours + add_time[1].minutes + add_time[2].seconds
          if etime <= a.end_time
            cdate = "#{day.strftime('%D')} #{stime.strftime('%r')} #{etime.strftime('%r')}"
            if future_dates.include?(cdate.to_s)
              future_dates -= [cdate.to_s]
            else
              data << [a.format_time(day, stime, etime), a.select_data(stime, etime, day)]
            end
          end
          stime = etime
        end
      end
    end
    data
  end

  def select_data(stime, etime, day)
    "#{id}^#^#{stime.strftime('%I:%M %P')}^#^#{etime.strftime('%I:%M %P')}^#^#{day.strftime('%Y-%m-%d')}"
  end

  def format_time(day, stime, etime)
    "#{day.strftime('%m/%d')} #{stime.strftime('%I:%M %P')} - #{
      etime.strftime('%I:%M %P')} with #{user.full_name}"
  end

  def time_difference
    ((end_time - start_time).hours / 3600).round
  end

  def week_day_format
    Date::DAYNAMES[day_of_week].to_date
  end

  def future_appointments
    user.appointments.where('start_time > ?', Time.now.end_of_day)
  end

  def collect_future_date_times
    future_appointments.map { |m| m.future_formatting_date }
  end

  def duration
    "#{day_of_week} #{start_time.strftime('%l:%M %P')} - #{end_time.strftime('%l:%M %P')}"
  end
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :authenticate_user!, :user_authenticated?
  before_action :set_availability, only: %i[show edit update destroy]
  skip_before_action :check_user_subscription, only: [:create, :destroy]

  # GET /availabilities or /availabilities.json
  def index
    @availabilities = Availability.all
  end

  # GET /availabilities/1 or /availabilities/1.json
  def show; end

  # GET /availabilities/new
  def new
    @availability = Availability.new
  end

  # GET /availabilities/1/edit
  def edit; end

  # POST /availabilities or /availabilities.json
  def create
    @availabilities = current_user.availabilities
    @availability = Availability.new(availability_params)
    @availability.user = current_user

    respond_to do |format|
      if @availability.save
        format.html { redirect_to demo_settings_path, notice: 'Availability was successfully updated.' }
        format.json { render :'demos/settings', status: :ok, location: @availability }
      else
        format.html { render 'demos/settings', status: :unprocessable_entity }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /availabilities/1 or /availabilities/1.json
  def update
    respond_to do |format|
      if @availability.update(availability_params)
        format.html { redirect_to @availability, notice: 'Availability was successfully updated.' }
        format.json { render :show, status: :ok, location: @availability }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availabilities/1 or /availabilities/1.json
  def destroy
    @availability.destroy
    respond_to do |format|
      format.html { redirect_to demo_settings_path, notice: 'Availability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_availability
    @availability = Availability.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def availability_params
    params.require(:availability).permit(:day_of_week, :start_time, :end_time)
  end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/views/availabilities/_form.html.erb
<%= form_with(model: availability) do |form| %>
  <% if availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(availability.errors.count, "error") %> prohibited this availability from being saved:</h2>

      <ul>
        <% availability.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :day_of_week %>
    <%= form.number_field :day_of_week %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/availabilities/edit.html.erb
<h1>Editing Availability</h1>

<%= render 'form', availability: @availability %>

<%= link_to 'Show', @availability %> |
<%= link_to 'Back', availabilities_path %>

app/views/availabilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Availabilities</h1>

<table>
  <thead>
    <tr>
      <th>Day of week</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @availabilities.each do |availability| %>
      <tr>
        <td><%= availability.day_of_week %></td>
        <td><%= availability.start_time %></td>
        <td><%= availability.end_time %></td>
        <td><%= link_to 'Show', availability %></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
        <td><%= link_to 'Destroy', availability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Availability', new_availability_path %>

app/views/availabilities/new.html.erb
<h1>New Availability</h1>

<%= render 'form', availability: @availability %>

<%= link_to 'Back', availabilities_path %>

app/views/availabilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day of week:</strong>
  <%= @availability.day_of_week %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @availability.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @availability.end_time %>
</p>

<%= link_to 'Edit', edit_availability_path(@availability) %> |
<%= link_to 'Back', availabilities_path %>